### ISSUE TITLE
Error in seq.default(16, nextSBlock - s_indicies[s] - 2, 2)

### ISSUE THREAD

**Issue by arthuc01** [GarrettLab-UF/LipidMatch#6]
First time user, I'm getting the following error using LipidMatch 2.0.2 under R 3.3.3

```
Error in seq.default(16, nextSBlock - s_indicies[s] - 2, 2) : 
  wrong sign in 'by' argument

```
Any suggestions what I might be doing wrong?

**Comment by arthuc01** [comment]
The error was arising because in line 1087

for (m in seq(16, nextSBlock-s_indicies[s]-2, 2)){

because nextSBlock-s_indicies[s]-2) was less than 16, enclosing this  for loop in an if statement to check gets it working again

**Comment by jeremykoelmel** [comment]
Great, feel free to push the change.
Usually I just recommend people to use the array filter in MSConvert to remove MS/MS spectra with 2 or less fragments (see manual under Agilent trouble shooting). But this is better if it is fixed in the code. 
Hope LipidMatch serves you well and sorry for not getting back to you!
